spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/file_manager"
    username: "file_manager"
    password: 1234

  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    me.hounds: debug

server:
  port: 9090